---
- name: Load Docker image on Ubuntu
  community.docker.docker_image:
    name: mcm/web-app
    tag: latest
    load_path: /tmp/mcm_web_app.tar

- name: Run Docker container on Ubuntu
  community.docker.docker_container:
    name: magboo_webapp_ubuntu
    image: mcm/web-app:latest
    ports:
      - "8080:80"
    state: started
    recreate: true

